stdb2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from user import urls as user_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^unittests/', include('unittests.urls', namespace='unittests')),
    url(r'^user/', include(user_urls, app_name='user', namespace='user-auth'))
]

unittests/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^dashboard/$', TemplateView.as_view(template_name='unittests/dashboard.html'),
        name='dashboard'),

    url(r'^$', views.TestListView.as_view(), name='test_list'),
    url(r'^tests/(?P<test_id>\d+)/$',
        views.TestDetails.as_view(), name='test_details'),
    url(r'^tests/(?P<pk>\d+)/update$',
        views.TestUpdate.as_view(), name='test_update'),
    url(r'^tests/(?P<test_id>\d+)/json/$',
        views.TestDetailsJson.as_view(), name='test_details_json'),
    url(r'^tests/(?P<test_id>\d+)/plot/$',
        views.TestPwrPlot.as_view(), name='test_pwr_plot'),
    url(r'^tests/(?P<test_id>\d+)/download/$',
        views.TestDownload.as_view(), name='test_download'),
    url(r'^tests/create$', views.TestCreate.as_view(), name='test_create'),
    url(r'^tests/(?P<pk>\d+)/delete$',
        views.TestDeleteView.as_view(), name='test_delete'),

    url(r'^(?P<pol_name>STRIP\d+)/$',
        views.PolarimeterDetails.as_view(), name='polarimeter_details'),

    url(r'^tests/(?P<test_id>\d+)/newadcoffset$',
        views.AdcOffsetAddView.as_view(), name='adc_create'),
    url(r'^tests/(?P<test_id>\d+)/newadcoffset/json$',
        views.AdcOffsetJsonView.as_view(), name='adc_create_json'),
    url(r'^tests/(?P<test_id>\d+)/newdetoutput$',
        views.DetOutputAddView.as_view(), name='detoutput_create'),
    url(r'^tests/(?P<test_id>\d+)/newdetoutput/json$',
        views.DetOutputJsonView.as_view(), name='detoutput_create_json'),
    url(r'^tests/(?P<test_id>\d+)/newbiases$',
        views.BiasesAddView.as_view(), name='biases_create'),
    url(r'^tests/(?P<test_id>\d+)/newbiases/json$',
        views.BiasesJsonView.as_view(), name='biases_create_json'),
    url(r'^tests/(?P<test_id>\d+)/newtemperature$',
        views.TemperatureAddView.as_view(), name='temperature_create'),
    url(r'^tests/(?P<test_id>\d+)/temperature/json$',
        views.TemperatureJsonView.as_view(), name='temperature_create_json'),
    url(r'^tests/(?P<test_id>\d+)/newtemperature/duplicatelast$',
        views.duplicate_last_temperature, name='temperature_duplicate_last'),

    url(r'^adcoffset/(?P<pk>\d+)/update$',
        views.AdcOffsetUpdateView.as_view(), name='adc_update'),
    url(r'^detoutput/(?P<pk>\d+)/update$',
        views.DetOutputUpdateView.as_view(), name='detoutput_update'),
    url(r'^biases/(?P<pk>\d+)/update$',
        views.BiasesUpdateView.as_view(), name='biases_update'),
    url(r'^temperature/(?P<pk>\d+)/update$',
        views.TemperatureUpdateView.as_view(), name='temperature_update'),

    url(r'^adcoffset/(?P<pk>\d+)/delete$',
        views.AdcOffsetDeleteView.as_view(), name='adc_delete'),
    url(r'^detoutput/(?P<pk>\d+)/delete$',
        views.DetOutputDeleteView.as_view(), name='detoutput_delete'),
    url(r'^biases/(?P<pk>\d+)/delete$',
        views.BiasesDeleteView.as_view(), name='biases_delete'),
    url(r'^temperature/(?P<pk>\d+)/delete$',
        views.TemperatureDeleteView.as_view(), name='temperature_delete'),

    url(r'^tnoise/$', views.TnoiseListView.as_view(), name='tnoise_list'),
    url(r'^tnoise/(?P<pk>\d+)$', views.TnoiseReport.as_view(), name='tnoise_report'),
    url(r'^tnoise/add/(?P<test_id>\d+)$',
        views.TnoiseAddView.as_view(), name='tnoise_create'),
    url(r'^tnoise/(?P<pk>\d+)/update$',
        views.TnoiseUpdateView.as_view(), name='tnoise_update'),
    url(r'^tnoise/(?P<pk>\d+)/delete$',
        views.TnoiseDeleteView.as_view(), name='tnoise_delete'),

    url(r'^bandpass/$', views.BandpassAnalysisListView.as_view(),
        name='bandpass_list'),
    url(r'^bandpass/(?P<pk>\d+)$',
        views.BandpassAnalysisReport.as_view(), name='bandpass_report'),
    url(r'^bandpass/add/(?P<test_id>\d+)$',
        views.BandpassAnalysisAddView.as_view(), name='bandpass_create'),
    url(r'^bandpass/(?P<pk>\d+)/update$',
        views.BandpassAnalysisUpdateView.as_view(), name='bandpass_update'),
    url(r'^bandpass/(?P<pk>\d+)/delete$',
        views.BandpassAnalysisDeleteView.as_view(), name='bandpass_delete'),

    url(r'^spectrum/$', views.SpectralAnalysisListView.as_view(), name='spectrum_list'),
    url(r'^spectrum/(?P<pk>\d+)$',
        views.SpectralAnalysisReport.as_view(), name='spectrum_report'),
    url(r'^spectrum/add/(?P<test_id>\d+)$',
        views.SpectralAnalysisAddView.as_view(), name='spectrum_create'),
    url(r'^spectrum/(?P<pk>\d+)/update$',
        views.SpectralAnalysisUpdateView.as_view(), name='spectrum_update'),
    url(r'^spectrum/(?P<pk>\d+)/delete$',
        views.SpectralAnalysisDeleteView.as_view(), name='spectrum_delete'),

    # REST API

    url(r'^api/tnoise/$', views.TnoiseAllData.as_view(), name='api-tnoise-all-data'),
    url(r'^api/tnoise/(?P<pk>\d+)$',
        views.TnoiseData.as_view(), name='api-tnoise-data'),

    url(r'^api/bandpass/$', views.BandpassAllData.as_view(),
        name='api-bandpass-all-data'),
    url(r'^api/bandpass/(?P<pk>\d+)$',
        views.BandpassData.as_view(), name='api-bandpass-data'),

    url(r'^api/spectrum/$', views.SpectrumAllData.as_view(),
        name='api-spectrum-all-data'),
    url(r'^api/spectrum/(?P<pk>\d+)$',
        views.SpectrumData.as_view(), name='api-spectrum-data'),

    url(r'^api/tests/STRIP(?P<num>\d+)/$', views.TestsByPolarimeter.as_view(),
        name='api-tests-polarimeter'),

    url(r'^api/tests/types/$', views.TestTypes.as_view(),
        name='api-tests-types'),
    url(r'^api/tests/types/(?P<pk>\d+)$', views.TestsByType.as_view(),
        name='api-tests-types'),

    url(r'^api/tests/users/$', views.UsersData.as_view(),
        name='api-tests-users'),
    url(r'^api/tests/countbydate/$', views.TestTimeTableData.as_view(),
        name='api-tests-countbydate'),
]

user/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(
        pattern_name='user-auth:login',
        permanent=False
    )),
    url(r'^login/$', auth_views.login,
        {'template_name': 'user/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {
        'template_name': 'user/logged_out.html',
        'extra_context': {
            'form': AuthenticationForm,
        }
    }, name='logout'),
]

unittests/models.py
# -*- encoding: utf-8 -*-

'''Database model for the "unittest" application

This module provides the definition of the database tables and fields used by
"unittest", the application which keeps track of the raw data and the analysis
results of the polarimetric unit tests done in Bicocca.

The core of the module is the "PolarimeterTest" class, which is typically
associated to one datafile acquired using the electronic board or to one set of
Excel files acquired using the Keithley apparatus. All the other classes provide
additional (and often optional) information about the test.abs

The main reason why the structure of tables seems so complicated stems from the
need of great versatility. Since no housekeeping information was recorded during
the tests, the code cannot assume that information such as amplifier biases,
housekeeping temperatures, and so on is available and ready to be put in the
database.
'''

from io import BytesIO
import logging
import os
from tempfile import NamedTemporaryFile

from django.conf import settings
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.files import File
from django.core.files.base import ContentFile
import h5py
import matplotlib as mpl

from jsonfield import JSONField

from .file_conversions import convert_data_file_to_h5
from .validators import validate_report_file_ext

mpl.use('Agg')
import matplotlib.pylab as plt

# Get an instance of a logger
LOGGER = logging.getLogger(__name__)


class TestType(models.Model):
    'Kind of test (e.g., Y-factor)'
    description = models.CharField(max_length=80)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = 'type of test'
        ordering = ['description']


class Operator(models.Model):
    'Person who has run a test'

    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


BAND_CHOICES = (
    ('Q', 'Q'),
    ('W', 'W'),
)

PHSW_STATES = (
    ('N/A', 'N/A'),
    ('0101', '0101'),
    ('0110', '0110'),
    ('switching', 'switching'),
    ('1010', '1010'),
    ('1001', '1001'),
)


def create_pwr_plot(hdf5_file_name, dpi=80):
    'Plot PWR data from an HDF5 file into an image'

    plt.figure(figsize=(512 / dpi, 384 / dpi), dpi=dpi)
    with h5py.File(hdf5_file_name, 'r') as h5_file:
        if not 'time_series' in h5_file:
            # Do not attempt to make plots from a file containing Keithley data
            return None

        dataset = h5_file['time_series']
        time = dataset['time_s']

        for idx, detector in enumerate(['Q1', 'U1', 'U2', 'Q2']):
            column = 'pwr_{0}_ADU'.format(detector)
            pwr_name = 'PWR{0}'.format(idx)
            plt.plot(
                time, dataset[column], label='{0} ({1})'.format(pwr_name, detector))

    plt.xlabel('Time [s]')
    plt.ylabel('Output [ADU]')
    plt.legend()

    # Save the image
    buffer = BytesIO()
    plt.savefig(buffer, format='png', bbox_inches='tight', dpi=dpi)

    return ContentFile(buffer.getvalue())


def update_hdf5_test_file_attrs(file_name, poltest):
    'Update HDF5 file attributes with information from a PolarimeterTest obj'

    if settings.HTTP_HOST and settings.HTTP_HOST != '':
        abs_url = ''.join([settings.HTTP_HOST,
                           poltest.get_absolute_url()])
    else:
        abs_url = poltest.get_absolute_url()

    with h5py.File(file_name, 'r+') as h5_file:
        for key, value in [('url', abs_url),
                           ('polarimeter', poltest.polarimeter_name),
                           ('cryogenic', poltest.cryogenic),
                           ('acquisition_date',
                            poltest.acquisition_date.strftime('%Y-%m-%d')),
                           ('band', poltest.band),
                           ('test_type', str(poltest.test_type))]:
            h5_file.attrs[key] = value


def get_polarimeter_name(num):
    return 'STRIP{0:02d}'.format(num)


class PolarimeterTest(models.Model):
    'A dedicated test done on one polarimeter'

    polarimeter_number = models.IntegerField(
        verbose_name='Number of the polarimeter')
    cryogenic = models.BooleanField(verbose_name='Cryogenic test')
    acquisition_date = models.DateField(
        verbose_name='Date of acquisition (YYYY-MM-DD)')
    data_file = models.FileField(max_length=1024, upload_to='unit_test_data/')
    short_description = models.CharField(max_length=140, blank=True,
                                         verbose_name='Short description (optional)')
    notes = models.TextField(verbose_name='Notes', blank=True)
    phsw_state = models.CharField(
        max_length=12, default='N/A', choices=PHSW_STATES)
    band = models.CharField(max_length=1, choices=BAND_CHOICES)

    pwr_plot = models.ImageField(
        max_length=1024, upload_to='plots/', blank=True)

    test_type = models.ForeignKey(TestType, on_delete=models.CASCADE)
    operators = models.ManyToManyField(Operator, related_name='tests')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='tests_owned', on_delete=models.PROTECT)
    creation_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return '{0} {1} ({2})'.format(
            self.polarimeter_name,
            self.test_type,
            self.acquisition_date,
        )

    @property
    def polarimeter_name(self):
        return get_polarimeter_name(self.polarimeter_number)

    @property
    def test_description(self):
        if self.short_description:
            return self.short_description
        else:
            return self.test_type.description

    def get_absolute_url(self):
        return reverse('unittests:test_details', kwargs={'test_id': self.pk})

    def get_download_url(self):
        return reverse('unittests:test_download', kwargs={'test_id': self.pk})

    def get_json_url(self):
        return reverse('unittests:test_details_json', kwargs={'test_id': self.pk})

    def get_delete_url(self):
        return reverse('unittests:test_delete', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if self.data_file:
            # Remove weird characters from the description of the test type
            test_type = ''.join(filter(str.isalpha,
                                       self.test_type.description))
            base_file_name = ('{polname}_{date}_{testtype}'
                              .format(polname=self.polarimeter_name,
                                      date=self.acquisition_date.strftime(
                                          '%Y-%m-%d'),
                                      testtype=test_type))
            hdf5_file_name = base_file_name + '.h5'
            LOGGER.debug('going to create a temporary HDF5 file in "%s"',
                         hdf5_file_name)
            with NamedTemporaryFile(suffix='.h5', delete=False) as temporary_file:
                tmp_file_name = temporary_file.name
                convert_data_file_to_h5(
                    self.data_file.name, self.data_file, temporary_file.name)
                image_file = create_pwr_plot(temporary_file.name)

            LOGGER.debug('importing HDF5 file "%s" into the database',
                         hdf5_file_name)
            with open(tmp_file_name, 'rb') as temporary_file:
                self.data_file = File(temporary_file, hdf5_file_name)

                if image_file:
                    self.pwr_plot.save(base_file_name + '.png',
                                       image_file, save=False)

                super(PolarimeterTest, self).save(*args, **kwargs)

            os.remove(tmp_file_name)
            LOGGER.debug(
                'HDF5 file "%s" imported in the database and removed, new file is "%s"',
                hdf5_file_name, self.data_file.name)

            update_hdf5_test_file_attrs(os.path.join(
                settings.MEDIA_ROOT, self.data_file.name), self)
            LOGGER.debug('metadata for file "%s" have been updated',
                         self.data_file.name)
        else:
            super(PolarimeterTest, self).save(*args, **kwargs)

    def to_dict(self):
        'Create a dictionary containing a summary of the test (useful for the REST API)'

        return {
            'id': self.pk,
            'polarimeter_number': self.polarimeter_number,
            'test_type': self.test_type.pk,
            'description': self.test_description,
            'absolute_url': self.get_absolute_url(),
            'download_url': self.get_download_url(),
            'json_url': self.get_json_url(),
        }

    class Meta:
        verbose_name = 'test of a polarimetric unit'
        ordering = ['polarimeter_number', 'acquisition_date']
        get_latest_by = 'acquisition_date'


class AdcOffset(models.Model):
    'Offset configuration used for the four ADCs'

    test = models.ForeignKey(to=PolarimeterTest, on_delete=models.CASCADE)
    q1_adu = models.IntegerField(verbose_name='PWR0 (Q1) offset [ADU]')
    u1_adu = models.IntegerField(verbose_name='PWR1 (U1) offset [ADU]')
    u2_adu = models.IntegerField(verbose_name='PWR2 (U2) offset [ADU]')
    q2_adu = models.IntegerField(verbose_name='PWR3 (Q2) offset [ADU]')

    def __str__(self):
        return 'PWR0={0} ADU, PWR1={1} ADU, PWR2={2} ADU, PWR3={3} ADU'.format(
            self.q1_adu,
            self.u1_adu,
            self.u2_adu,
            self.q2_adu
        )

    def get_absolute_url(self):
        return self.test.get_absolute_url()

    class Meta:
        verbose_name = 'values of the four ADC offsets'


def dict_to_adc_offset_list(data):
    offsets = data['adc_offsets']
    if type(offsets) is dict:
        # We have just one set of outputs, so let's build a list with one element
        offsets = [offsets]

    return [AdcOffset(
        q1_adu=x['q1_adu'],
        u1_adu=x['u1_adu'],
        u2_adu=x['u2_adu'],
        q2_adu=x['q2_adu'],
    ) for x in offsets]

unittests/templates/unittests/adddetoutput.html
{%extends "unittests/base.html" %}

{% block title %}
LSPE/Strip DB: Add detector outputs
{% endblock %}

{% block contents %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table id="add-det-outputs">
        {{ form.as_table }}
    </table>

    <input type="submit" value="Add detector outputs to STRIP{{polarimeter_number}} test"/>
</form>

{% endblock %}

unittests/templates/unittests/addtnoise.html
{%extends "unittests/base.html" %}

{% block title %}
LSPE/Strip DB: Add Tnoise result
{% endblock %}

{% block contents %}
<h1>Add new noise temperature estimate</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table id="add-tnoise">
        {{ form.as_table }}
    </table>

    <input type="submit" value="Create"/>
</form>

{% endblock %}

unittests/templates/unittests/generic_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm"/>
</form>
{% endblock %}

unittests/templates/unittests/polarimetertest_create.html
{% extends "base.html" %}

{% block title %}
LSPE/Strip DB: Add new test
{% endblock %}

{% block content %}
<h2>Polarimetric test</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div id="add-test-table">
        {{ form.as_p }}
    </div>

    <input type="submit" value="Submit"/>
</form>

<script>
    $( function() {
        $("#id_acquisition_date").datepicker({
            showButtonPanel: true,
            dateFormat: "yy-mm-dd"
        });
    } );

    var data_file_obj = document.getElementById('id_data_file');
    console.log(`data_file_obj = ${data_file_obj}`);
    data_file_obj.addEventListener('change', handleFiles, false);

    function handleFiles(ev) {
        if (! ev) var ev = window.event;

        var selected_file = data_file_obj.files[0];
        if (! selected_file) return;

        /* Update the «Notes» text */
        var file_size_kb = Math.round(selected_file.size / 1024);
        $('#id_notes').text(`The source data file was «${selected_file.name}» (${file_size_kb} kB)`);

        /* Update the «Acquisition date» field */
        date_match = selected_file.name.match(/SCI\d{6}/i);
        if (date_match) {
            var year = 2000 + parseInt(date_match[0].substring(3, 5));
            var month = parseInt(date_match[0].substring(5, 7));
            var day = parseInt(date_match[0].substring(7, 9));

            $('#id_acquisition_date').datepicker('setDate', `${year}-${month}-${day}`)
        }

        /* Update the «Polarimeter number» field */
        polnum_match = selected_file.name.match(/STRIP\d{2}/i);
        if (polnum_match) {
            var polnum = parseInt(polnum_match[0].substring(5, 7));
            $('#id_polarimeter_number').val(polnum);
        }
    }
</script>

{% endblock %}

unittests/templates/unittests/polarimetertest_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
LSPE/Strip DB: List of tests
{% endblock %}

{% block content %}
<div class="content">
    <div style="margin-top: 1em">
        <h2>Polarimetric unit tests</h2>
        <p>Number of tests in the database: {{ num_of_tests }}, belonging to {{ polarimeter_tests.items | length }} polarimeters.</p>
    </div>

    <div class="action-bar">
        <ul>
            <li><a href="{% url 'unittests:test_create' %}">Add test</a></li>
        </ul>
    </div>

    <div>
        {% if polarimeter_tests %}
        <input type="text" id="polarimeter-test-filter" onkeyup="filterPolarimeterTable()" placeholder="Filter…">

        <ul id="polarimeter-test-list">
            {% for cur_pol, cur_list_of_tests in polarimeter_tests.items %}
            <li>
                <span class="polarimeter-name">
                    <a href="{% url 'unittests:polarimeter_details' cur_pol %}">{{ cur_pol }}</a>
                </span><span class="dropdown-icon" onclick="toggle_ul(this);">&#9661;</span>
                <ul class="polarimeter-test-sublist item_hide" hidden="true">
                    {% for cur_test in cur_list_of_tests %}
                    <li>
                        <div class="test-definition">
                            <a href="{% url 'unittests:test_update' cur_test.id %}"><!--
                            --><img src="{% static 'site/edit.svg' %}" width="32" height="32" alt="Edit"/><!--
                            --></a>
                            &nbsp;
                            <a href="{% url 'unittests:test_delete' cur_test.id %}"><!--
                            --><img src="{% static 'site/delete.svg' %}" width="32" height="32" alt="Delete"/><!--
                            --></a>
                            <span class="test-description">
                                <a href="{% url 'unittests:test_details' cur_test.id %}">
                                    {% if cur_test.short_description %}
                                        {{ cur_test.short_description }}
                                    {% else %}
                                        <i>{{ cur_test.test_type }}</i>
                                    {% endif %}
                                </a> ({{ cur_test.acquisition_date }})
                            </span>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>

<script>
    /* This is like "split", but it does not leave empty strings in the array */
    function splitAtSpaces(str) {
        return str.split(" ").filter(function (x) { return x != "" })
    }

    function filterPolarimeterTable() {
        var test_table = document.getElementById("polarimeter-test-table-body");
        var rows = test_table.getElementsByTagName("tr");

        var filter_field = document.getElementById("polarimeter-test-filter");
        var filters = splitAtSpaces(filter_field.value.toUpperCase());
        if (filters.length == 0) {
            /* No filter: make all rows visible */
            for (rowidx = 0; rowidx < rows.length; rowidx++) {
                rows[rowidx].style.display = "";
            }

            return;
        }

        for (rowidx = 0; rowidx < rows.length; rowidx++) {
            cell = rows[rowidx].getElementsByTagName("td");
            if (! cell) continue;

            var found = false;

            cellloop:
            for (cellidx = 0; cellidx < cell.length; cellidx++) {
                /* We might have more than one word to search, so we must loop over them */
                for (filtidx = 0; filtidx < filters.length; filtidx++) {
                    /* Note that this way of filtering joins filter words using OR */
                    if (cell[cellidx].innerHTML.toUpperCase().indexOf(filters[filtidx]) > -1) {
                        found = true;
                        break cellloop;
                    }
                }
            }
            if (found) {
                rows[rowidx].style.display = "";
            } else {
                rows[rowidx].style.display = "none";
            }
        }
    }

    function toggle_ul(obj) {
        var list_of_children = $(obj).next('ul');
        if(list_of_children.is(":visible")) {
            $(".dropdown-icon", obj).html("&#9661;");
            list_of_children.slideUp(); 
        } else {
            $(".dropdown-icon", obj).html("&#9651;");
            list_of_children.slideDown();
        }
    }
</script>
{% endblock %}

unittests/templates/unittests/spectral_analysis_create.html
{% extends "base.html" %}

{% block title %}
LSPE/Strip DB: Add spectral analysis results
{% endblock %}

{% block content %}
<h1>Spectral analysis results</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div id="spectral-analysis-create">
        {{ form.as_p }}
    </div>

    <input type="submit" value="Submit"/>
</form>

{% endblock %}

unittests/templates/unittests/tnoise_list.html
{% extends "base.html" %}

{% block title %}
LSPE/Strip DB: List of tests
{% endblock %}

{% block content %}
<h2>Noise temperature estimates</h2>

<p>Number of reports in the database: {{ tnoise_tests | length }}</p>

<div id="tnoise-plot" style="height: 580px"></div>

<table>
    <thead>
        <th>Polarimeter</th>
        <th>Test</th>
        <th>T<sub>noise</sub> [K]</th>
        <th>G<sub>Q1</sub> [ADU/K]</th>
        <th>G<sub>U1</sub> [ADU/K]</th>
        <th>G<sub>U2</sub> [ADU/K]</th>
        <th>G<sub>Q2</sub> [ADU/K]</th>
        <th>Analysis date</th>
        <th>Report</th>
        <th>JSON</th>
    </thead>
    <tbody>
        {% for cur in tnoise_tests %}
        <tr>
            {% with cur_result=cur.analysis_results %}
            <td>
                <a href="{% url 'unittests:polarimeter_details' cur.test.polarimeter_name %}">
                    {{ cur.test.polarimeter_name }}
                </a>
            </td>
            <td>
                <a href="{% url 'unittests:test_details' cur.test.id %}">{{ cur.test.test_type }} (PHSW {{ cur.test.phsw_state }})</a>
            </td>
            <td>{{ cur_result.tnoise.mean|floatformat:1 }}±{{ cur_result.tnoise.std|floatformat:1 }}</a></td>
            <td>{{ cur_result.gain_q1.mean|floatformat:0 }}±{{ cur_result.gain_q1.std|floatformat:0 }}</a></td>
            <td>{{ cur_result.gain_u1.mean|floatformat:0 }}±{{ cur_result.gain_u1.std|floatformat:0 }}</a></td>
            <td>{{ cur_result.gain_u2.mean|floatformat:0 }}±{{ cur_result.gain_u2.std|floatformat:0 }}</a></td>
            <td>{{ cur_result.gain_q2.mean|floatformat:0 }}±{{ cur_result.gain_q2.std|floatformat:0 }}</a></td>
            <td><time datetime="{{cur_result.analysis_date|date:"Y-m-d"}}">{{cur_result.analysis_date}}</time></td>
            <td>
                {% if cur.report_file %}
                    <a href="{% url 'unittests:tnoise_report' cur.id %}">Report</a>
                {% else %}
                    (None)
                {% endif %}
            </td>
            <td><a href="{% url 'unittests:api-tnoise-data' cur.id %}">Link</a></td>
            {% endwith %}
        </tr>
        {% endfor %}
    </tbody>
</table>

<script>
    $.ajax({
        method: "GET",
        url: "{% url 'unittests:api-tnoise-all-data' %}",
        success: function(data) {
            pol_name = data.polarimeters;
            results = data.results;

            plot_tnoise_chart(pol_name, results);
        },
        error: function(error_data) {
            console.log("error:");
            console.log(error_data);
        }
    });

    function plot_tnoise_chart(pol_name, results) {
        mean_tnoise = [];
        text = [];
        for(var pol_idx = 0; pol_idx < results.length; pol_idx++) {
            var tnoise = 0.0;
            var pol_results = results[pol_idx];
            for(var res_idx = 0; res_idx < pol_results.length; res_idx++) {
                tnoise += results[pol_idx][res_idx].tnoise.mean;
            }
            tnoise /= pol_results.length;
            console.log('tnoise: ' + tnoise.toString())
            mean_tnoise.push(tnoise);
            text.push('mean of ' + pol_results.length.toString() + ' estimate(s)');
        }

        var data = [{
            x: mean_tnoise,
            y: pol_name,
            text: text,
            type: "bar",
            orientation: "h"
        }];

        Plotly.newPlot("tnoise-plot", data, { });
    }

</script>
{% endblock %}